### ISSUE TITLE
JFlex dependency version

### ISSUE THREAD

**Issue by raboof** [gshakhn/maven-jflex-plugin#1]
I'm confused about the JFlex dependency: the README appears to suggest I need to get '1.4.3.idea.12.0.4' from IntelliJ, but the pom.xml depends on 1.5.0-SNAPSHOT.

Where do I find this 1.5.0-SNAPSHOT version?

**Comment by gshakhn** [comment]
AFAIK there is no 1.5.0-SNAPSHOT version.

The idea branch depends on JFlex 1.4.3.idea.12.0.4 (see https://github.com/gshakhn/maven-jflex-plugin/blob/idea/pom.xml). This is the version that the README installs.

I'm not sure if the JFlex jar has changed in IntelliJ since 12.0.4, but feel free to update the JFlex jar file name as it's installed in maven to match your version of IntelliJ

**Comment by raboof** [comment]
Sorry I missed that i should have checked out the idea branch, though it's right there in the README... my bad ;)
